### ISSUE TITLE
导入tf_geometirc时报错

### ISSUE THREAD

**Issue by chenci107** [CrawlScript/tf_geometric#35]
根据要求在python=3.7的条件下安装了tf_geometirc,导入时报错如下：
import imp
WARNING:tensorflow:From /home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/__init__.py:10: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/__init__.py", line 12, in <module>
    from . import nn, utils, data, datasets, layers, sparse
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/nn/__init__.py", line 7, in <module>
    from .conv.gcn import gcn, gcn_norm_adj, gcn_build_cache_for_graph, gcn_norm_edge, gcn_cache_normed_edge
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/nn/conv/gcn.py", line 3, in <module>
    from tf_geometric.sparse.sparse_adj import SparseAdj
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/sparse/__init__.py", line 3, in <module>
    from .sparse_adj import SparseAdj
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/sparse/sparse_adj.py", line 7, in <module>
    from tf_sparse import SparseMatrix
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_sparse/__init__.py", line 13, in <module>
    from . import layers, utils
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_sparse/layers/__init__.py", line 3, in <module>
    from .dropout import Dropout
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_sparse/layers/dropout.py", line 3, in <module>
    from tf_sparse.sparse_matrix import SparseMatrix
  File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_sparse/sparse_matrix.py", line 12, in <module>
    from tensorflow.python.ops.linalg.sparse.sparse_csr_matrix_ops import sparse_tensor_to_csr_sparse_matrix, \
ModuleNotFoundError: No module named 'tensorflow.python.ops.linalg.sparse'

**Comment by hujunxianligong** [comment]
请使用tensorflow 2.4+版本。方便的话可以加微信群发自我的华为手机-------- 原始邮件 --------发件人： chenci107 ***@***.***>日期： 2021年12月9日周四 下午2:47收件人： CrawlScript/tf_geometric ***@***.***>抄送： Subscribed ***@***.***>主    题： [CrawlScript/tf_geometric] 导入tf_geometirc时报错 (Issue #35)

根据要求在python=3.7的条件下安装了tf_geometirc,导入时报错如下：

import imp

WARNING:tensorflow:From /home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/init.py:10: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

Traceback (most recent call last):

File "", line 1, in 

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/init.py", line 12, in 

from . import nn, utils, data, datasets, layers, sparse

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/nn/init.py", line 7, in 

from .conv.gcn import gcn, gcn_norm_adj, gcn_build_cache_for_graph, gcn_norm_edge, gcn_cache_normed_edge

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/nn/conv/gcn.py", line 3, in 

from tf_geometric.sparse.sparse_adj import SparseAdj

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/sparse/init.py", line 3, in 

from .sparse_adj import SparseAdj

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_geometric/sparse/sparse_adj.py", line 7, in 

from tf_sparse import SparseMatrix

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_sparse/init.py", line 13, in 

from . import layers, utils

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_sparse/layers/init.py", line 3, in 

from .dropout import Dropout

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_sparse/layers/dropout.py", line 3, in 

from tf_sparse.sparse_matrix import SparseMatrix

File "/home/chenci/anaconda3/envs/tfG/lib/python3.7/site-packages/tf_sparse/sparse_matrix.py", line 12, in 

from tensorflow.python.ops.linalg.sparse.sparse_csr_matrix_ops import sparse_tensor_to_csr_sparse_matrix, 

ModuleNotFoundError: No module named 'tensorflow.python.ops.linalg.sparse'

**Comment by chenci107** [comment]
我的其他部分代码是用1.x写的，所以想问一下有没有在1.x下能用的tf_geometric版本？谢谢～

**Comment by chenci107** [comment]
> 我的其他部分代码是用1.x写的，所以想问一下有没有在1.x下能用的tf_geometric版本？谢谢～

**Comment by hujunxianligong** [comment]
最近的版本主要支持2.x，对1.x的支持也是在Eager Execution模式下的。如果你是Session那种，还是选择其他框架吧，谢谢！

**Comment by chenci107** [comment]
> 最近的版本主要支持2.x，对1.x的支持也是在Eager Execution模式下的。如果你是Session那种，还是选择其他框架吧，谢谢！

我用tf_upgrade_v2将原来的1.x代码转成了2.x,在2.x下代码可跑，但是原来的placeholder和session都还在，请问用tfg写的代码能和我之前的代码结合起来吗？如果不行的话，麻烦问一下您有推荐的其他适合tf1.x的框架吗？谢谢～

**Comment by hujunxianligong** [comment]
不是很清楚其他的框架有没有问题。但是一般理解从1迁移到2的逻辑很简单吧，简单学一下就行了
